import Head from 'next/head'
import styles from '../../styles/pages/Login.module.css'
import { useSession, signIn, signOut } from 'next-auth/client'
import { useState } from 'react';
import { useRouter } from 'next/router'
import { Loading } from '../../components/Loading';
import Swal from 'sweetalert2';

export default function Login() {
    const [session] = useSession();
    const [isLoading, setIsLoading] = useState(false);
    const router  = useRouter();
    
    const handleSignin = async (e) => {
        e.preventDefault() 
        signIn("google")
    }

    const handleSignout = (e) => {
        e.preventDefault()
        signOut()  
    }

    const enterHome = async (e) => {
        e.preventDefault()
        if(session){
            setIsLoading(true)
            await fetch('/api/authPetiano', {
                method: 'POST',
                headers: {
                'Accept': 'application/json, text/plain, */*',
                'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    name: session?.user?.name,
                    photo: session?.user?.image,
                    email: session?.user?.email,
                }),
            }).then((res) => {
                if(res.status == 200){
                    console.log("criado e logado")
                    router.push("/Home")
                }
                else if(res.status == 400){
                    setIsLoading(false)
                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000,
                        timerProgressBar: true,
                        didOpen: (toast) => {
                          toast.addEventListener('mouseenter', Swal.stopTimer)
                          toast.addEventListener('mouseleave', Swal.resumeTimer)
                        }
                    })
                      
                    Toast.fire({
                        icon: 'error',
                        title: 'Você não está cadastrado em nossa plataforma!'
                    })
                    console.log("Não habilitado para cadastro")
                }
                else if(res.status == 202){
                    console.log("ja criado e logando agora")
                    router.push("/Home")
                }
            })         
        }  
    }
    
    return (
        <div className={styles.container}>
            <Head>
                <title>Avaliação 360</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {
                !isLoading ? (
                    <>
                        <img className={styles.people} src="ImagemLogin.svg" alt="Imagem de pessoas trabalhando" />
            
                        <div className={styles.boxLog}>
                            <img src="LogoNomePet.svg" alt="Logo do PET" />
                            <h3>AVALIAÇÃO 360</h3>

                                {
                                    session? (
                                        <div className={styles.perfil} >
                                            <div className={styles.header}>
                                                <div  className={styles.titles}>
                                                    <h1>Bem vinda(o),</h1>
                                                    <h2>{session.user.name}</h2>
                                                </div>
                                                
                                                <img src={session.user.image} alt="icone do google" />
                                            </div>                                       
                                            <button className={styles.buttonLogin} onClick={enterHome}>                                              
                                                ENTRAR
                                            </button>
                                            <button className={styles.buttonLogin} style={{backgroundColor: "#A4303F", color: "white"}} onClick={handleSignout}>                                           
                                                SAIR
                                            </button>                                      
                                        </div>      
                                    ):( 
                                        <button className={styles.buttonLogin} onClick={handleSignin}>
                                            <img src="iconGoogle.svg" alt="icone do google" />
                                            Login com o Google
                                        </button>     
                                    )
                                }                     
                        </div>
                    </>
                ) : <Loading />
            }
        </div>
    )
}